from django.urls import path

from monitoring.hrms_views import (
    add_case_note_action,
    add_nursing_note_action,
    add_vitals_action,
    admin_dashboard,
    alerts_page,
    audit_logs_page,
    assign_role_action,
    close_alert_action,
    close_case_action,
    create_user_action,
    disable_user_action,
    export_audit_csv,
    export_case_report_action,
    hrms_login,
    hrms_logout,
    hrms_root,
    investigations_page,
    nurse_dashboard,
    open_patient_record_action,
    patient_record_default_redirect,
    patient_record_page,
    patient_search_page,
    reset_password_action,
    run_detection_action,
    run_evaluation_action,
    roles_permissions_page,
    save_permissions_action,
    save_system_settings_action,
    signoff_handover_action,
    shift_handover_page,
    system_settings_page,
    triage_alert_action,
    user_flow_page,
    users_page,
)
from monitoring.hrms_views import export_anomaly_histogram_csv
from monitoring.views import (
    AccessLogListView,
    AnomalyListView,
    EvaluationListView,
    PatientCreateView,
    PatientDeleteView,
    PatientDetailView,
    PatientListView,
    PatientUpdateView,
    run_detection_view,
    run_evaluation_view,
)


urlpatterns = [
    path("", hrms_root, name="home"),
    path("hrms/", hrms_root, name="hrms-root"),
    path("hrms/login/", hrms_login, name="hrms-login"),
    path("hrms/logout/", hrms_logout, name="hrms-logout"),
    path("hrms/admin-dashboard/", admin_dashboard, name="hrms-admin-dashboard"),
    path("hrms/actions/run-detection/", run_detection_action, name="hrms-run-detection"),
    path("hrms/actions/run-evaluation/", run_evaluation_action, name="hrms-run-evaluation"),
    path("hrms/users/", users_page, name="hrms-users"),
    path("hrms/users/create/", create_user_action, name="hrms-user-create"),
    path("hrms/users/<int:user_id>/disable/", disable_user_action, name="hrms-user-disable"),
    path("hrms/users/<int:user_id>/reset-password/", reset_password_action, name="hrms-user-reset-password"),
    path("hrms/users/<int:user_id>/assign-role/", assign_role_action, name="hrms-user-assign-role"),
    path("hrms/roles-permissions/", roles_permissions_page, name="hrms-roles-permissions"),
    path("hrms/roles-permissions/save/", save_permissions_action, name="hrms-save-permissions"),
    path("hrms/system-settings/", system_settings_page, name="hrms-system-settings"),
    path("hrms/system-settings/save/", save_system_settings_action, name="hrms-save-system-settings"),
    path("hrms/nurse-dashboard/", nurse_dashboard, name="hrms-nurse-dashboard"),
    path("hrms/patient-search/", patient_search_page, name="hrms-patient-search"),
    path("hrms/patient-access/<int:patient_id>/", open_patient_record_action, name="hrms-open-patient-record"),
    path("hrms/patient-record/", patient_record_default_redirect, name="hrms-patient-record-default"),
    path("hrms/patient-record/<int:pk>/", patient_record_page, name="hrms-patient-record"),
    path("hrms/patient-record/<int:pk>/add-vitals/", add_vitals_action, name="hrms-add-vitals"),
    path("hrms/patient-record/<int:pk>/add-note/", add_nursing_note_action, name="hrms-add-note"),
    path("hrms/shift-handover/", shift_handover_page, name="hrms-shift-handover"),
    path("hrms/shift-handover/signoff/", signoff_handover_action, name="hrms-signoff-handover"),
    path("hrms/audit-logs/", audit_logs_page, name="hrms-audit-logs"),
    path("hrms/audit-logs/export.csv", export_audit_csv, name="hrms-export-audit-csv"),
    path("hrms/alerts/", alerts_page, name="hrms-alerts"),
    path("hrms/alerts/<int:alert_id>/triage/", triage_alert_action, name="hrms-triage-alert"),
    path("hrms/alerts/<int:alert_id>/close/", close_alert_action, name="hrms-close-alert"),
    path("hrms/investigations/", investigations_page, name="hrms-investigations"),
    path("hrms/investigations/<int:case_id>/add-note/", add_case_note_action, name="hrms-add-case-note"),
    path("hrms/investigations/<int:case_id>/close/", close_case_action, name="hrms-close-case"),
    path("hrms/investigations/<int:case_id>/export-report/", export_case_report_action, name="hrms-export-case-report"),
    path("hrms/anomaly-distribution/export.csv", export_anomaly_histogram_csv, name="hrms-export-anomaly-histogram"),
    path("hrms/user-flow/", user_flow_page, name="hrms-user-flow"),
    path("patients/", PatientListView.as_view(), name="patient-list"),
    path("patients/new/", PatientCreateView.as_view(), name="patient-create"),
    path("patients/<int:pk>/", PatientDetailView.as_view(), name="patient-detail"),
    path("patients/<int:pk>/edit/", PatientUpdateView.as_view(), name="patient-update"),
    path("patients/<int:pk>/delete/", PatientDeleteView.as_view(), name="patient-delete"),
    path("access-logs/", AccessLogListView.as_view(), name="accesslog-list"),
    path("anomalies/", AnomalyListView.as_view(), name="anomaly-list"),
    path("evaluations/", EvaluationListView.as_view(), name="evaluation-list"),
    path("actions/run-detection/", run_detection_view, name="run-detection"),
    path("actions/run-evaluation/", run_evaluation_view, name="run-evaluation"),
]
