from django.core.management.base import BaseCommand, CommandError

from monitoring.models import AccessLog
from monitoring.services import evaluate_detector, format_evaluation_table
from monitoring.synthetic import generate_synthetic_access_logs


class Command(BaseCommand):
    help = "Evaluate anomaly detection against labeled synthetic anomalies."

    def add_arguments(self, parser):
        parser.add_argument(
            "--contamination",
            type=float,
            default=0.08,
            help="Isolation Forest contamination value.",
        )
        parser.add_argument(
            "--autogenerate",
            action="store_true",
            help="Generate synthetic labeled logs if none exist.",
        )
        parser.add_argument("--events", type=int, default=3000, help="Events for autogenerated dataset.")
        parser.add_argument(
            "--anomaly-rate",
            type=float,
            default=0.08,
            help="True anomaly ratio for autogenerated dataset.",
        )

    def handle(self, *args, **options):
        logs = AccessLog.objects.filter(is_simulated=True).order_by("accessed_at")
        if not logs.exists():
            if options["autogenerate"]:
                self.stdout.write("No simulated logs found. Generating synthetic dataset...")
                generate_synthetic_access_logs(
                    events=options["events"],
                    anomaly_rate=options["anomaly_rate"],
                    reset_simulated=True,
                )
                logs = AccessLog.objects.filter(is_simulated=True).order_by("accessed_at")
            else:
                raise CommandError(
                    "No simulated logs found. Run generate_synthetic_logs or pass --autogenerate."
                )

        result = evaluate_detector(logs, contamination=options["contamination"])
        self.stdout.write(self.style.SUCCESS("Evaluation complete."))
        self.stdout.write(format_evaluation_table(result))
