# Generated by Django 5.1.7 on 2026-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_hrms_integration_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='monitoring__user_id_f3416b_idx',
            old_name='monitoring_a_user_id_58b714_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='monitoring__role_sn_a661c8_idx',
            old_name='monitoring_a_role_sn_00d35b_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='monitoring__is_simu_1653cb_idx',
            old_name='monitoring_a_is_simu_8a1935_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='monitoring__is_flag_89911a_idx',
            old_name='monitoring_a_is_fla_d97689_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='monitoring__action__e6fc68_idx',
            old_name='monitoring_a_action__fd2739_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='monitoring__departm_178f06_idx',
            old_name='monitoring_a_departm_a82f25_idx',
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='role_snapshot',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], default='nurse', max_length=20),
        ),
    ]
