# Generated by Django 5.1.7 on 2026-03-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "monitoring",
            "0003_rename_monitoring_a_user_id_58b714_idx_monitoring__user_id_f3416b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesslog",
            name="action",
            field=models.CharField(
                choices=[
                    ("view", "View"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("download", "Download"),
                ],
                max_length=20,
            ),
        ),
    ]
