# Generated by Django 5.1.7 on 2026-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0004_alter_accesslog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="download_lock_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="download_locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
